//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TaskManager.Data.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_Task
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TB_Task()
        {
            this.TB_TaskList = new HashSet<TB_TaskList>();
            this.TB_TaskList1 = new HashSet<TB_TaskList>();
        }
    
        public int ID { get; set; }
        public string description { get; set; }
        public Nullable<int> statusID { get; set; }
        public Nullable<int> userID { get; set; }
        public Nullable<System.DateTime> date { get; set; }
    
        public virtual TB_TaskStatus TB_TaskStatus { get; set; }
        public virtual TB_User TB_User { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TB_TaskList> TB_TaskList { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TB_TaskList> TB_TaskList1 { get; set; }
    }
}
