USE [TaskManager]
GO

/****** Object:  Table [dbo].[TB_TaskStatus]    Script Date: 02/05/2018 09:04:22 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[TB_TaskStatus](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[status] [nchar](50) NULL,
 CONSTRAINT [PK_TB_TaskStatus] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

